### ISSUE TITLE
This does not work, it says something about contact the owner..

### ISSUE THREAD

**Issue by 3raden** [6K6666/roblox-hwid-ban-remover#2]

**Comment by 6K6666** [comment]
Can you send a screenshot of the full error message?

**Comment by 3raden** [comment]
![image](https://user-images.githubusercontent.com/64098772/134746799-a5e8a46f-14e2-4181-a2ee-94f0c2496185.png)

**Comment by 6K6666** [comment]
It’s possible it might be patched. I made this with a help of a person i’m not longer friends with over a year ago and things may have changed by now. I have a new pc and i’m no longer HWID banned so i can’t really test this theory. There’s not much i can do, sorry!

**Comment by 3raden** [comment]
Someone has forked it and has fixed the issue, this is the link. https://github.com/pogpoggers/roblox-hwid-ban-remover
